# Experiment general info
name: "OV_SQA3D"
rng_seed: 42
num_gpu: 4
mode: "train"
note: ""
# Choose keywords to feature your saving directory
naming_keywords: ["dataloader.batchsize", "task", "note", "time"]
base_dir: "results"
exp_dir: ""

resume: False

debug:
  flag: False
  hard_debug: False
  debug_size: 20

logger:
  name: "wandb"
  entity: "yem"

# dataset details
data:
  train: ['ScanNetSQA3D']
  val: ['ScanNetSQA3D']
  test: ['ScanNetSQA3D']
  ScanNetSQA3D:
    train:
      use_unanswer: True
    val:
      use_unanswer: True
    test:
      use_unanswer: True
  scan_family_base: "dataset/ScanNet"

# task details: 'pretrain', 'scanrefer', 'referit3d', 'scanqa', 'default'
task: 'SQA3D'
data_wrapper:
  train: 'ScanFamilyDatasetWrapperQA'
  val: 'ScanFamilyDatasetWrapperQA'
  test: 'ScanFamilyDatasetWrapperQA'

# Training details
trainer: "DefaultTrainer"
pretrain_ckpt_path: "results/sceneverse_scannet_exp1_b16_Pretrain_all_scannet_training_run1/cur_best_v1/ckpt/ckpt_15.pth"

# dataloader details
# batchsize is per-GPU -> global batch = 64 x 4 = 256
dataloader:
  batchsize: 64
  num_workers: 4

solver:
  gradient_accumulation_steps: 1
  epochs_per_save: 100
  epochs_per_eval: 1
  lr: 2e-4  # sqrt-scaled from 1e-4 for 4x global batch (4 GPU)
  grad_norm: 5.0
  epochs: 100
  optim:
    name: "AdamW"
    args:
      betas: [0.9, 0.98]
  sched:
    name: "warmup_cosine"
    args:
      warmup_steps: 5000

eval:
  name: "SQA3DEval"
  save: False

# Model details
model:
  name: UniScene3D
  vision:
    lr: 2e-4  # sqrt-scaled from 1e-4 for 4x global batch (4 GPU)
  heads:
    head_list: ["qa_head"]
    qa_head:
      name: "QAHeadV1"
      args:
        hidden_size: 768
        num_answers: 706
  loss_list: [
      "answer_loss"
  ]
  vis_loss_list: [
      "answer_loss"
  ]
